# Chapter_2_Solutions

## Question 1

### Step 1. Download the dataset

In [3]:
!dandi download https://dandiarchive.org/dandiset/000130/draft

PATH                                       SIZE     DONE            DONE% CHECKSUM STATUS          MESSAGE
dandiset.yaml                                                                      done            updated
sub-Haydn/sub-Haydn_desc-test_ecephys.nwb  1.6 MB   1.6 MB           100%    ok    done
sub-Haydn/sub-Haydn_desc-train_ecephys.nwb 14.1 MB  14.1 MB          100%    ok    done
Summary:                                   15.7 MB  15.7 MB                        3 done          1 updated
                                                    100.00%
2021-11-30 15:21:22,149 [    INFO] Logs saved in /Users/ashley/Library/Logs/dandi-cli/20211130232107Z-5807.log

### Step 2. Read one NWB file

In [4]:
# import necessary packages
from pynwb import NWBHDF5IO

# read the NWB file
filename = '000130/sub-Haydn/sub-Haydn_desc-train_ecephys.nwb'

io = NWBHDF5IO(filename, 'r')
nwb_file = io.read()

### Step 3. Get meta data

In [11]:
print(nwb_file.related_publications)
print(nwb_file.experiment_description)

('http://dx.doi.org/10.1016/j.neuron.2019.06.012',)
Cognitive timing task in which subject attempts to reproduce interval between two cues

### Step 4. Get intervals data

In [14]:
intervals = nwb_file.intervals

# Pull out trials and assign it as a dataframe
interval_trials_df = intervals['trials'].to_dataframe()
interval_trials_df.head()

,start_time,stop_time,fix_on_time,fix_time,target_on_time,ready_time,set_time,go_time,target_acq_time,reward_time,...,is_eye,theta,ts,tp,fix_time_dur,target_time_dur,iti,reward_dur,is_outlier,split
id,,,,,,,,,,,,,,,,,,,,,
0,0.5160,3.4825,0.5160,0.5500,1.0835,1.7835,2.5835,3.4170,3.4175,3.45,...,False,0.0,800.0,850.963,534.818565,689.495657,500.0,40.271583,False,train
1,3.9995,7.1495,3.9995,4.0335,4.6335,5.2670,6.1670,7.0795,7.0800,7.10,...,False,180.0,900.0,930.199,607.886039,632.193947,500.0,54.341259,False,train
2,7.6660,11.7995,7.6660,7.7000,8.6000,9.5500,10.7500,11.7715,11.7715,11.80,...,False,180.0,1200.0,1038.650,903.837023,943.257413,500.0,7.252778,False,val
3,12.3165,12.3830,12.3165,12.3505,NaN,NaN,NaN,NaN,NaN,NaN,...,False,0.0,1200.0,-2400.000,688.639206,943.257413,500.0,0.000700,True,none
4,13.9160,17.7160,13.9160,14.0670,14.9335,15.2335,16.1335,17.1895,17.1895,NaN,...,False,0.0,900.0,1073.084,866.004231,298.540437,500.0,0.000700,False,train

In [15]:
# return the description of each col in our dataframe
for col in interval_trials_df:
    print(col,':',intervals['trials'][col].description)

start_time : Start time of epoch, in seconds
stop_time : Stop time of epoch, in seconds
fix_on_time : Time when the fixation cue on the display turns on
fix_time : Time when the animal fixates on the fixation cue
target_on_time : Time of target presentation
ready_time : Time of ready cue delivery
set_time : Time of set cue presentation
go_time : Time of monkey response, either with an eye saccade or joystick movement
target_acq_time : Time of target acquisition
reward_time : Time of monkey reward, if there was one
bad_time : Time of trial failure, if the trial was unsuccessful
is_short : Whether short prior (True) or long prior (False)
is_eye : Whether motion to target was with hand (False) or eye (True)
theta : Whether the target was on the right (0) or left (180)
ts : Time between ready and set stimuli, in ms
tp : Time between set stimulus and monkey go response, in ms
fix_time_dur : Time between animal fixation and target onset, in ms
target_time_dur : Time between target onset and ready, in ms
iti : Inter-trial interval, in ms. Equal to 500 for trials sampled from short prior and 1220 for trials sampled from long prior
reward_dur : Duration of reward, in ms
is_outlier : Whether a trial's tp is considered an outlier using probabilistic mixture model
split : Trial split that the trial belongs to for the Neural Latents Benchmark. Can be "train", "val", "test", or "none"

### Step 5. Get neural data

In [19]:
units = nwb_file.units
units_df = units.to_dataframe()
print('Number of units: ',len(units_df))
units_df.head()

Number of units:  54

,heldout,spike_times,obs_intervals
id,,,
1001,False,"[2.697, 2.743, 2.754, 2.766, 2.78, 2.81, 2.863...","[[0.0, 740.01], [740.1, 1519.462], [1519.6, 22..."
1002,False,"[0.232, 0.781, 0.836, 1.034, 1.163, 1.358, 1.4...","[[0.0, 740.01], [740.1, 1519.462], [1519.6, 22..."
1003,False,"[1.466, 1.557, 1.566, 1.937, 1.957, 2.264, 2.3...","[[0.0, 740.01], [740.1, 1519.462], [1519.6, 22..."
1004,False,"[0.871, 0.945, 1.039, 1.168, 1.179, 1.185, 1.1...","[[0.0, 740.01], [740.1, 1519.462], [1519.6, 22..."
1007,True,"[0.036, 0.122, 0.606, 0.661, 0.733, 0.821, 0.9...","[[0.0, 740.01], [740.1, 1519.462], [1519.6, 22..."

## Question 2

In [ ]:
# This code snippet isn't functional out of context, but it follows from Chapter 2.2
fair_units_df = units_df[units_df['quality']=='Fair']
fair_units_df.head()